[build]
  command = "npm run build:skip-type"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { GITHUB_PAGES = "true" }
